# Generated by Django 3.1.7 on 2021-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
