# Generated by Django 3.1.7 on 2021-04-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in kg', max_digits=5),
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_profile', models.ImageField(blank=True, upload_to='store/profile', verbose_name='Store profile photo')),
                ('store_cover', models.ImageField(blank=True, upload_to='store/cover', verbose_name='Store cover photo')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
        ),
    ]
