# Generated by Django 3.1.7 on 2021-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customershippingaddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
