# Generated by Django 3.1.7 on 2021-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customershippingaddress_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customershippingaddress',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='full_name',
            field=models.CharField(max_length=400),
        ),
    ]
